version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    container_name: auth-service-postgres
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service-go-app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      PORT: "3000"
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  postgres_data:
